name: geoh2
channels:
  - defaults
  - conda-forge
  - bioforge

dependencies:
  - python
  - atlite=0.2.10
  - cartopy
  - gdal=3
  - geopy
  - geopandas
  - matplotlib
  - numpy
  - openpyxl
  - pandas = 1.5.3
  - pip
  - pypsa = 0.21.3
  - shapely = 1.8.4
  - snakemake
  - xarray = 0.20.1

  - pip:
    - cdsapi
    - fiona
    - pyproj
    - rasterio!= 1.2.10
    - pillow == 9.2.0

